spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/movies
    username: sa
    initialization-mode: always

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher